// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJB2BQ003VQBrtp3zORc3spwSlVGINiCg',
    appId: '1:27856438720:web:80a5e0341d9defd9f6b425',
    messagingSenderId: '27856438720',
    projectId: 'dtc-bus-community',
    authDomain: 'dtc-bus-community.firebaseapp.com',
    storageBucket: 'dtc-bus-community.appspot.com',
    measurementId: 'G-24LD1FMPBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYKbjA_2TXdSzDxgTWR4SMqpqjdryq4a8',
    appId: '1:27856438720:android:b65e603fe096eb39f6b425',
    messagingSenderId: '27856438720',
    projectId: 'dtc-bus-community',
    storageBucket: 'dtc-bus-community.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo20Ie_HjEY6loJSpcMh6VjYiOoehN5Uw',
    appId: '1:27856438720:ios:6d94c3fe077d6042f6b425',
    messagingSenderId: '27856438720',
    projectId: 'dtc-bus-community',
    storageBucket: 'dtc-bus-community.appspot.com',
    iosBundleId: 'com.example.dtcBusCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo20Ie_HjEY6loJSpcMh6VjYiOoehN5Uw',
    appId: '1:27856438720:ios:6d94c3fe077d6042f6b425',
    messagingSenderId: '27856438720',
    projectId: 'dtc-bus-community',
    storageBucket: 'dtc-bus-community.appspot.com',
    iosBundleId: 'com.example.dtcBusCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJB2BQ003VQBrtp3zORc3spwSlVGINiCg',
    appId: '1:27856438720:web:c5a9cfa30ef2e6b1f6b425',
    messagingSenderId: '27856438720',
    projectId: 'dtc-bus-community',
    authDomain: 'dtc-bus-community.firebaseapp.com',
    storageBucket: 'dtc-bus-community.appspot.com',
    measurementId: 'G-EX9GV6BZXP',
  );
}
